services:
  postgres:
    image: postgres:18
    container_name: hms-postgres
    environment:
      POSTGRES_USER: charith
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: patient_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - hms-network

  mysql:
    image: mysql:8.0
    container_name: hms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: doctor_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hms-network

  postgres-appointment:
    image: postgres:18
    container_name: hms-postgres-appointment
    environment:
      POSTGRES_USER: charith
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: appointment_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - appointment_data:/var/lib/postgresql
    networks:
      - hms-network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: hms-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - hms-network

volumes:
  postgres_data:
  mysql_data:
  appointment_data:

networks:
  hms-network:
    driver: bridge
